version: "3.8"

volumes:
  app-logs: {}
  grafana-storage: {}

services:
  am:
    container_name: am
    image: autometrics/am:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "6789:6789"
      - "9090:9090"
    command: "start http://otel-collector:9464/metrics host.docker.internal:9464 host.docker.internal:9465 host.docker.internal:9466"
    environment:
      - LISTEN_ADDRESS=0.0.0.0:6789
    restart: unless-stopped
    volumes:
      - app-logs:/var/log
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888" # expose container metrics in prometheus format
      - "55680:55680"
      - "55679:55679"
    restart: unless-stopped
  push-gateway:
    container_name: push-gateway
    image: ghcr.io/zapier/prom-aggregation-gateway:latest
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../grafana/config.ini:/etc/grafana/grafana.ini
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - ../grafana/provisioning:/etc/grafana/provisioning
