---
name: Lint and test

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11", "pypy3.10"]
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with dev
      - name: Check code formatting
        run: poetry run black .
      - name: Lint lib code
        run: poetry run mypy src --enable-incomplete-feature=Unpack
      - name: Lint lib examples
        run: poetry run mypy examples --enable-incomplete-feature=Unpack
      - name: Run tests
        run: poetry run pytest -n auto
